version: '3.8'

services:
  adonis_app:
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: sh -c 'node ace migration:fresh --seed && dumb-init node ace serve --watch'